# -*- coding: utf-8 -*-
"""edgeAi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKRUVjdELaIsCPjJXPHn4ibOycyPlC-D
"""

!pip install ultralytics
!pip install lap>=0.5.12

from ultralytics import YOLO
model = YOLO('yolov8n.pt')

from google.colab import files
uploaded = files.upload()  # opens a file picker — select your video
video_path = list(uploaded.keys())[0]

import time

# --- Config ---
owners_away = True  # simulate "house owners not home" — you'll wire this to a real toggle later
CONSECUTIVE_FRAMES_THRESHOLD = 5  # require detection across multiple frames to avoid false alerts
alert_counter = 0
alert_sent = False

def send_alert(person_count):
    # Placeholder — swap this for a real Telegram/webhook call
    print(f"🚨 ALERT: {person_count} person(s) detected while house is away!")

# --- Run inference frame-by-frame on your video ---
videoframes = model(video_path, stream=True, classes=[0], vid_stride=5, verbose=False)
for frame_result in videoframes:
    person_count = len(frame_result.boxes)

    if owners_away and person_count > 0:
        alert_counter += 1
        if alert_counter >= CONSECUTIVE_FRAMES_THRESHOLD and not alert_sent:
            send_alert(person_count)
            alert_sent = True
    else:
        alert_counter = 0
        alert_sent = False  # room is empty again — ready to alert on the next intrusion